spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 20MB
  application:
    name: easyetl-app
  datasource:
    druid:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1
      mysql:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/easyetl?characterEncoding=utf8
        username: root
        password: root
  quartz:
    job-store-type: memory
    jdbc.initialize-schema: never
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8003
datasync:
  channel:
    capacity: 5000
    batchSize: 1000
swagger:
  enable: true
